# Generated by Django 3.1.7 on 2021-06-21 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210621_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pageslog',
            old_name='page',
            new_name='pages',
        ),
        migrations.RenameField(
            model_name='pageslog',
            old_name='user',
            new_name='users',
        ),
    ]
