# Generated by Django 3.1.7 on 2021-06-21 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0005_auto_20210621_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='pages',
            field=models.ManyToManyField(null=True, to='pages.Page'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to=settings.AUTH_USER_MODEL),
        ),
    ]
