# Generated by Django 3.1.7 on 2021-06-22 02:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0008_auto_20210621_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='pages',
            field=models.ManyToManyField(to='pages.Page'),
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ManyToManyField(related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
