# Generated by Django 3.1.7 on 2021-06-24 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20210622_0028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-updated'], 'verbose_name': 'Subscripcion', 'verbose_name_plural': 'Subscripciones'},
        ),
        migrations.RemoveField(
            model_name='page',
            name='cupos',
        ),
        migrations.AddField(
            model_name='page',
            name='cupo',
            field=models.SmallIntegerField(default=0, verbose_name='Cupo'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='pages',
            field=models.ManyToManyField(related_name='act', to='pages.Page'),
        ),
    ]
