# Generated by Django 3.1.7 on 2021-06-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20210626_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=200, verbose_name='Día')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Día',
                'verbose_name_plural': 'Días',
                'ordering': ['-order'],
            },
        ),
    ]
