# Generated by Django 3.1.7 on 2021-06-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20210628_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='mostrar',
            field=models.BooleanField(default=1, verbose_name='Mostrar día en calendario'),
        ),
        migrations.AlterField(
            model_name='page',
            name='modalidad',
            field=models.BooleanField(default=0, verbose_name='Online: Tildado - Presencial: Destildado'),
        ),
    ]
