# Generated by Django 3.1.7 on 2021-06-29 04:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_page_flyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Horario'),
        ),
    ]
