# Generated by Django 3.1.7 on 2021-06-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20210629_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Horario'),
        ),
    ]
