# Generated by Django 3.1.7 on 2021-06-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_page_nuevo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='modalidad',
            field=models.BooleanField(default=0, verbose_name='Online'),
        ),
        migrations.AlterField(
            model_name='page',
            name='nuevo',
            field=models.BooleanField(default=0, verbose_name='Nuevo'),
        ),
    ]
