# Generated by Django 3.1.7 on 2021-07-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_auto_20210629_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='suspendida',
            field=models.BooleanField(default=0, verbose_name='Suspendida'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='pages',
            field=models.ManyToManyField(related_name='pages', to='pages.Page'),
        ),
    ]
