# Generated by Django 3.1.7 on 2021-07-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_auto_20210701_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='dia',
            field=models.ManyToManyField(related_name='get_dias', to='pages.Day', verbose_name='dias'),
        ),
    ]
