# Generated by Django 3.1.7 on 2021-07-01 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_page_dia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['content'], 'verbose_name': 'página', 'verbose_name_plural': 'páginas'},
        ),
        migrations.RemoveField(
            model_name='page',
            name='order',
        ),
    ]
