# Generated by Django 3.1.7 on 2021-07-02 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_auto_20210701_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='horaDesde',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Hora desde'),
        ),
        migrations.AddField(
            model_name='page',
            name='horaHasta',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Hora hasta'),
        ),
    ]
