# Generated by Django 3.1.7 on 2021-07-02 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_auto_20210702_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='dia',
        ),
        migrations.AddField(
            model_name='page',
            name='dia',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.day', verbose_name='dias'),
        ),
    ]
