# Generated by Django 3.1.7 on 2021-07-02 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_auto_20210702_0059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['dia__order', 'horaDesde', '-title'], 'verbose_name': 'página', 'verbose_name_plural': 'páginas'},
        ),
    ]
