# Generated by Django 3.1.7 on 2021-07-03 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0030_auto_20210702_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='content',
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de realización')),
                ('anotados', models.ManyToManyField(related_name='get_anotados', to=settings.AUTH_USER_MODEL)),
                ('asistencias', models.ManyToManyField(related_name='get_asistencias', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.page', verbose_name='Actividad')),
            ],
        ),
    ]
