# Generated by Django 3.1.7 on 2021-07-03 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_auto_20210703_0251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historial',
            options={'ordering': ['-fecha', 'page'], 'verbose_name': 'Historial', 'verbose_name_plural': 'Historial'},
        ),
    ]
