# Generated by Django 3.1.7 on 2021-07-03 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_auto_20210703_0254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['dia__order', 'horaDesde', '-title'], 'verbose_name': 'actividad', 'verbose_name_plural': 'actividades'},
        ),
    ]
