# Generated by Django 3.1.7 on 2021-07-04 02:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0034_remove_historial_anotados'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='anotados',
            field=models.ManyToManyField(related_name='get_anotados', to=settings.AUTH_USER_MODEL),
        ),
    ]
