# Generated by Django 3.1.7 on 2021-07-05 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0037_auto_20210705_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='asistencias',
        ),
        migrations.AddField(
            model_name='historial',
            name='asistentes',
            field=models.ManyToManyField(blank=True, related_name='get_asistentes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historial',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagina', to='pages.page', verbose_name='Actividad'),
        ),
    ]
