# Generated by Django 3.1.7 on 2021-07-07 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_auto_20210706_0022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historial',
            options={'ordering': ['-fecha', 'page'], 'verbose_name': 'Asistencia', 'verbose_name_plural': 'Asistencias'},
        ),
    ]
