# Generated by Django 3.1.7 on 2021-07-07 00:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0040_auto_20210707_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='anotados',
            field=models.ManyToManyField(blank=True, related_name='get_anotados', to=settings.AUTH_USER_MODEL),
        ),
    ]
