# Generated by Django 3.1.7 on 2021-07-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0041_auto_20210707_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='mostrar',
        ),
        migrations.RemoveField(
            model_name='page',
            name='suspendida',
        ),
        migrations.AddField(
            model_name='page',
            name='activa',
            field=models.BooleanField(default=1, verbose_name='Activa'),
        ),
    ]
