# Generated by Django 3.1.7 on 2021-07-31 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('pages', '0042_auto_20210707_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.provincia'),
        ),
    ]
