# Generated by Django 3.1.7 on 2021-07-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0044_auto_20210731_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='clave',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Activa'),
        ),
        migrations.AddField(
            model_name='page',
            name='secreta',
            field=models.BooleanField(default=0, verbose_name='Es secreta?'),
        ),
    ]
