# Generated by Django 3.1.7 on 2021-07-31 19:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0045_auto_20210731_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='textoExtraMail',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texto extra del mail'),
        ),
        migrations.AlterField(
            model_name='page',
            name='clave',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Clave'),
        ),
    ]
