# Generated by Django 3.1.7 on 2021-08-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0047_auto_20210804_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='horaDesde',
            field=models.FloatField(blank=True, null=True, verbose_name='Hora desde'),
        ),
        migrations.AlterField(
            model_name='page',
            name='horaHasta',
            field=models.FloatField(blank=True, null=True, verbose_name='Hora hasta'),
        ),
    ]
