# Generated by Django 3.1.7 on 2021-08-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0049_auto_20210804_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='horaDesde',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora desde'),
        ),
        migrations.AlterField(
            model_name='page',
            name='horaHasta',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora hasta'),
        ),
    ]
