# Generated by Django 3.1.7 on 2021-08-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0050_auto_20210804_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='get_pages', to='pages.Category', verbose_name='categorias'),
        ),
    ]
