# Generated by Django 3.1.7 on 2021-08-06 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0051_auto_20210804_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='respuesta',
        ),
        migrations.AlterField(
            model_name='page',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='get_pages', to='pages.Category', verbose_name='categorias'),
        ),
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('pregunta', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Pregunta')),
                ('respuesta', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Respuesta')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagina_cuestionario', to='pages.page', verbose_name='Actividad')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuestionario',
                'verbose_name_plural': 'Cuestionarios',
                'ordering': ['updated'],
            },
        ),
    ]
