# Generated by Django 3.1.7 on 2021-08-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0052_auto_20210806_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuestionario',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='cuestionario',
            name='respuesta',
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='pregunta1',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Pregunta1'),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='pregunta2',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Pregunta2'),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='pregunta3',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Pregunta3'),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='pregunta4',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Pregunta4'),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='pregunta5',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Pregunta5'),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='respuesta1',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Respuesta1'),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='respuesta2',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Respuesta2'),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='respuesta3',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Respuesta3'),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='respuesta4',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Respuesta4'),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='respuesta5',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Respuesta5'),
        ),
    ]
