# Generated by Django 3.1.7 on 2021-08-07 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0054_auto_20210806_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='pregunta',
        ),
    ]
