# Generated by Django 3.1.7 on 2021-08-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0056_auto_20210808_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuestionariorespuesta',
            name='pregunta10',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Pregunta10'),
        ),
        migrations.AddField(
            model_name='cuestionariorespuesta',
            name='pregunta11',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Pregunta11'),
        ),
        migrations.AddField(
            model_name='cuestionariorespuesta',
            name='pregunta12',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Pregunta12'),
        ),
        migrations.AddField(
            model_name='cuestionariorespuesta',
            name='pregunta13',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Pregunta13'),
        ),
        migrations.AddField(
            model_name='cuestionariorespuesta',
            name='pregunta14',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Pregunta14'),
        ),
        migrations.AddField(
            model_name='cuestionariorespuesta',
            name='pregunta15',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Pregunta15'),
        ),
        migrations.AddField(
            model_name='cuestionariorespuesta',
            name='pregunta16',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Pregunta16'),
        ),
        migrations.AddField(
            model_name='cuestionariorespuesta',
            name='pregunta17',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Pregunta17'),
        ),
        migrations.AddField(
            model_name='cuestionariorespuesta',
            name='pregunta18',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Pregunta18'),
        ),
        migrations.AddField(
            model_name='cuestionariorespuesta',
            name='pregunta19',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Pregunta19'),
        ),
        migrations.AddField(
            model_name='cuestionariorespuesta',
            name='pregunta20',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Pregunta20'),
        ),
        migrations.AddField(
            model_name='cuestionariorespuesta',
            name='pregunta6',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Pregunta6'),
        ),
        migrations.AddField(
            model_name='cuestionariorespuesta',
            name='pregunta7',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Pregunta7'),
        ),
        migrations.AddField(
            model_name='cuestionariorespuesta',
            name='pregunta8',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Pregunta8'),
        ),
        migrations.AddField(
            model_name='cuestionariorespuesta',
            name='pregunta9',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Pregunta9'),
        ),
        migrations.AddField(
            model_name='cuestionariorespuesta',
            name='respuesta10',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Respuesta10'),
        ),
        migrations.AddField(
            model_name='cuestionariorespuesta',
            name='respuesta11',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Respuesta11'),
        ),
        migrations.AddField(
            model_name='cuestionariorespuesta',
            name='respuesta12',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Respuesta12'),
        ),
        migrations.AddField(
            model_name='cuestionariorespuesta',
            name='respuesta13',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Respuesta13'),
        ),
        migrations.AddField(
            model_name='cuestionariorespuesta',
            name='respuesta14',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Respuesta14'),
        ),
        migrations.AddField(
            model_name='cuestionariorespuesta',
            name='respuesta15',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Respuesta15'),
        ),
        migrations.AddField(
            model_name='cuestionariorespuesta',
            name='respuesta16',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Respuesta16'),
        ),
        migrations.AddField(
            model_name='cuestionariorespuesta',
            name='respuesta17',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Respuesta17'),
        ),
        migrations.AddField(
            model_name='cuestionariorespuesta',
            name='respuesta18',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Respuesta18'),
        ),
        migrations.AddField(
            model_name='cuestionariorespuesta',
            name='respuesta19',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Respuesta19'),
        ),
        migrations.AddField(
            model_name='cuestionariorespuesta',
            name='respuesta20',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Respuesta20'),
        ),
        migrations.AddField(
            model_name='cuestionariorespuesta',
            name='respuesta6',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Respuesta6'),
        ),
        migrations.AddField(
            model_name='cuestionariorespuesta',
            name='respuesta7',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Respuesta7'),
        ),
        migrations.AddField(
            model_name='cuestionariorespuesta',
            name='respuesta8',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Respuesta8'),
        ),
        migrations.AddField(
            model_name='cuestionariorespuesta',
            name='respuesta9',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Respuesta9'),
        ),
    ]
