# Generated by Django 3.1.7 on 2021-08-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0057_auto_20210809_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuestionario',
            name='pregunta10',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='pregunta11',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='pregunta12',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='pregunta13',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='pregunta14',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='pregunta15',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='pregunta16',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='pregunta17',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='pregunta18',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='pregunta19',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='pregunta20',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='pregunta6',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='pregunta7',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='pregunta8',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='pregunta9',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='pregunta1',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='pregunta2',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='pregunta3',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='pregunta4',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='pregunta5',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name=''),
        ),
    ]
