# Generated by Django 3.1.7 on 2023-06-13 12:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0062_page_con_preinscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='asunto_mail',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Asunto del mail'),
        ),
        migrations.AddField(
            model_name='page',
            name='con_mail_personalizado',
            field=models.BooleanField(default=False, verbose_name='Tiene mail personalizado?'),
        ),
        migrations.AddField(
            model_name='page',
            name='cuerpo_mail',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Cuerpo del mail'),
        ),
    ]
