# Generated by Django 3.1.7 on 2023-06-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0063_auto_20230613_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='mostrar',
            field=models.BooleanField(default=True, verbose_name='Mostrar'),
        ),
    ]
