# Generated by Django 3.1.7 on 2023-06-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0064_day_mostrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
    ]
