# Generated by Django 3.1.7 on 2023-06-28 22:46

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('pages', '0066_auto_20230626_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurrentPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('horaDesde', models.TimeField(blank=True, null=True, verbose_name='Hora desde')),
                ('horaHasta', models.TimeField(blank=True, null=True, verbose_name='Hora hasta')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descripción')),
                ('textoExtraMail', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texto extra del mail')),
                ('con_mail_personalizado', models.BooleanField(default=False, verbose_name='Con mail personalizado')),
                ('asunto_mail', models.CharField(blank=True, max_length=200, null=True, verbose_name='Asunto del mail')),
                ('cuerpo_mail', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Cuerpo del mail')),
                ('flyer', models.ImageField(blank=True, null=True, upload_to=pages.models.custom_upload_to)),
                ('fechaDesde', models.DateField(blank=True, null=True, verbose_name='Fecha desde')),
                ('fechaHasta', models.DateField(blank=True, null=True, verbose_name='Fecha hasta')),
                ('cupo', models.SmallIntegerField(default=0, verbose_name='Cupo')),
                ('modalidad', models.BooleanField(default=False, verbose_name='Online')),
                ('nuevo', models.BooleanField(default=False, verbose_name='Nuevo')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('dias', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=100, verbose_name='Días')),
                ('secreta', models.BooleanField(default=False, verbose_name='Tiene clave?')),
                ('clave', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Clave')),
                ('con_preinscripcion', models.BooleanField(default=False, verbose_name='Tiene preinscripción?')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición')),
                ('categories', models.ManyToManyField(blank=True, related_name='get_recurrent_pages', to='pages.Category', verbose_name='Categorias')),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.colaborador')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.provincia')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.responsable')),
            ],
            options={
                'verbose_name': 'Página recurrente',
                'verbose_name_plural': 'Páginas recurrentes',
                'ordering': ['fechaDesde'],
            },
        ),
    ]
