# Generated by Django 3.1.7 on 2023-06-28 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0067_recurrentpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurrentpage',
            options={'ordering': ['fechaDesde'], 'verbose_name': 'Actividad recurrente', 'verbose_name_plural': 'Actividades recurrentes'},
        ),
    ]
