# Generated by Django 3.1.7 on 2023-06-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0068_auto_20230628_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrentpage',
            name='dias',
            field=models.CharField(max_length=100, verbose_name='Días'),
        ),
    ]
