# Generated by Django 3.1.7 on 2023-06-29 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0069_auto_20230629_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='page', to='pages.subscription'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='pages',
            field=models.ManyToManyField(related_name='page_subscriptions', to='pages.Page'),
        ),
    ]
