# Generated by Django 3.1.7 on 2023-06-29 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0070_auto_20230629_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='recurrent_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='pages', to='pages.recurrentpage'),
        ),
    ]
