"""
Django settings for webhillel project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["www.hillelargentina.org.ar", "127.0.0.1",'localhost',]
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    "registration.apps.RegistrationConfig",
    "location.apps.LocationConfig",
    "profiles.apps.ProfilesConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.sites",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "ckeditor",
    "core",
    "pages.apps.PagesConfig",
    "social.apps.SocialConfig",

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',  # Google OAuth
    'allauth.socialaccount.providers.facebook',  # Facebook OAuth
]
AUTHENTICATION_BACKENDS = [
    "registration.backends.EmailVerifiedBackend",
    'django.contrib.auth.backends.ModelBackend',  # Default authentication
    'allauth.account.auth_backends.AuthenticationBackend',  # django-allauth
]


if DEBUG:
#    SITE_ID = 2
    SITE_ID = 5
else:
    SITE_ID = 3


SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': '998343550118-b4o62mn48v1g638294a7pdar0ht9n07s.apps.googleusercontent.com',
          'secret': os.getenv('GOOGLE_OAUTH_CLIENT_SECRET'),
            'key': ''
        }
    }
}
 
#LOGIN_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'
ACCOUNT_AUTHENTICATION_METHOD = "email" 
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "optional"
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_AUTO_SIGNUP = True

SOCIALACCOUNT_ADAPTER = "webhillel.adapters.MySocialAccountAdapter"

DBBACKUP_STORAGE = "django.core.files.storage.FileSystemStorage"
DBBACKUP_STORAGE_OPTIONS = {"location": BASE_DIR / "backup"}

SOCIALACCOUNT_LOGIN_ON_GET = True
ACCOUNT_LOGOUT_ON_GET = True

STATICFILES_STORAGE = "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"

 
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    "django.middleware.gzip.GZipMiddleware",
]
ROOT_URLCONF = "webhillel.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS":  [BASE_DIR / "templates"],  # Ensure it includes the custom folder
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "registration.processors.ctx_dict",
                "social.processors.ctx_dict",
                "profiles.processors.ctx_dict",
            ],
        },
    },
]
 

WSGI_APPLICATION = "webhillel.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = "es"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = False

DATE_FORMAT = "d-m-Y"


# Login Redirect
LOGIN_REDIRECT_URL = "home"  # 'pages:pages'
LOGOUT_REDIRECT_URL = "home"


# emails
if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_FILE_PATH = BASE_DIR / "send_emails"
    EMAIL_HOST = "smtp.gmail.com"
    EMAIL_HOST_USER = "infohillel@gmail.com"
    EMAIL_HOST_PASSWORD = "zftsqbzhgeuqmzrz"
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
else:
    # Aqui hay que configurar un email real para producción
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_FILE_PATH = BASE_DIR / "send_emails"
    EMAIL_HOST = "smtp.gmail.com"
    EMAIL_HOST_USER = "infohillel@gmail.com"
    EMAIL_HOST_PASSWORD = "zftsqbzhgeuqmzrz"
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True

    pass


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "static"

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
