# Generated by Django 3.1.7 on 2021-06-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20210409_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='celular',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dni',
            field=models.TextField(blank=True, null=True),
        ),
    ]
