# Generated by Django 3.1.7 on 2021-06-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20210619_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fechaNacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='provincia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
