# Generated by Django 3.1.7 on 2021-06-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20210628_1251'),
        ('registration', '0004_auto_20210619_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='categories',
            field=models.ManyToManyField(related_name='get_user_pages', to='pages.Category', verbose_name='categorias'),
        ),
        migrations.AddField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición'),
        ),
    ]
