# Generated by Django 3.1.7 on 2021-06-28 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20210628_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='provincias',
        ),
        migrations.AlterField(
            model_name='profile',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.provincia'),
        ),
    ]
