# Generated by Django 3.1.7 on 2021-06-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20210628_1251'),
        ('registration', '0010_auto_20210628_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='get_user_pages', to='pages.Category', verbose_name='Intereses'),
        ),
    ]
