# Generated by Django 3.1.7 on 2021-06-28 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_auto_20210628_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='provinciaOld',
        ),
    ]
