# Generated by Django 3.1.7 on 2021-06-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_remove_profile_provinciaold'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='validado',
            field=models.BooleanField(default=0, verbose_name='Perfil validado'),
        ),
    ]
