# Generated by Django 3.1.7 on 2021-07-08 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_auto_20210708_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dni',
        ),
        migrations.AddField(
            model_name='profile',
            name='apellido',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nombre',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Whatsapp'),
        ),
    ]
