# Generated by Django 3.1.7 on 2021-07-08 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_auto_20210708_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='experienciaComunitaria',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='onward',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.fechaonward', verbose_name='¿Viajaste a Onward? ¿Cuándo?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='taglit',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.fechataglit', verbose_name='¿Viajaste a Taglit? ¿Cuándo?'),
        ),
    ]
