# Generated by Django 3.1.7 on 2021-07-12 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_auto_20210710_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='onward',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.fechaonward', verbose_name='¿Viajaste a Onward? ¿Cuándo?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='taglit',
            field=models.ForeignKey(blank=True, default='NO', null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.fechataglit', verbose_name='¿Viajaste a Taglit? ¿Cuándo?'),
        ),
    ]
