# Generated by Django 3.1.7 on 2021-08-04 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('registration', '0023_auto_20210731_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.provincia', verbose_name='provincia'),
        ),
    ]
