# Generated by Django 3.1.7 on 2021-08-08 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_auto_20210804_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='celular',
            new_name='whatsapp',
        ),
    ]
