# Generated by Django 3.2.6 on 2021-09-03 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0025_auto_20210808_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropuestaInteres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propuesta', models.CharField(max_length=200, verbose_name='Propuesta')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Orden')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'FechaOnward',
                'verbose_name_plural': 'FechasOnward',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TematicaInteres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propuesta', models.CharField(max_length=200, verbose_name='Tematica')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Orden')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'FechaOnward',
                'verbose_name_plural': 'FechasOnward',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='propuestasInteres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.propuestainteres'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tematicasInteres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.tematicainteres'),
        ),
    ]
