# Generated by Django 3.2.6 on 2021-09-03 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0026_auto_20210903_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propuestainteres',
            options={'ordering': ['order'], 'verbose_name': 'PropuestaInteres', 'verbose_name_plural': 'PropuestasInteres'},
        ),
        migrations.AlterModelOptions(
            name='tematicainteres',
            options={'ordering': ['order'], 'verbose_name': 'TematicaInteres', 'verbose_name_plural': 'TematicasInteres'},
        ),
        migrations.RenameField(
            model_name='propuestainteres',
            old_name='propuesta',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='tematicainteres',
            old_name='propuesta',
            new_name='nombre',
        ),
    ]
