# Generated by Django 3.2.6 on 2021-09-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0027_auto_20210903_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='propuestasInteres',
        ),
        migrations.AddField(
            model_name='profile',
            name='propuestasInteres',
            field=models.ManyToManyField(blank=True, null=True, to='registration.PropuestaInteres'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tematicasInteres',
        ),
        migrations.AddField(
            model_name='profile',
            name='tematicasInteres',
            field=models.ManyToManyField(blank=True, null=True, to='registration.TematicaInteres'),
        ),
    ]
