# Generated by Django 3.2.6 on 2021-09-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0028_auto_20210903_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='propuestasInteres',
            field=models.ManyToManyField(to='registration.PropuestaInteres'),
        ),
    ]
