# Generated by Django 3.2.6 on 2021-09-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0029_alter_profile_propuestasinteres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tematicasInteres',
            field=models.ManyToManyField(to='registration.TematicaInteres'),
        ),
    ]
