# Generated by Django 3.2.6 on 2021-11-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0030_alter_profile_tematicasinteres'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporadaOnward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.BooleanField(verbose_name='En temporada')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de modificación')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'TemporadaOnward',
                'verbose_name_plural': 'TemporadaOnward',
                'ordering': ['temporada'],
            },
        ),
    ]
