# Generated by Django 3.2.6 on 2022-03-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0031_temporadaonward'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='observaciones',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
