# Generated by Django 3.1.7 on 2023-06-21 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0033_alter_profile_observaciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propuestainteres',
            options={'verbose_name': 'PropuestaInteres', 'verbose_name_plural': 'PropuestasInteres'},
        ),
        migrations.AlterModelOptions(
            name='tematicainteres',
            options={'verbose_name': 'TematicaInteres', 'verbose_name_plural': 'TematicasInteres'},
        ),
    ]
