# Generated by Django 3.1.7 on 2021-04-03 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='social',
            new_name='Link',
        ),
    ]
