# Generated by Django 3.1.7 on 2021-06-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20210403_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de modificacion'),
        ),
    ]
