# Generated by Django 3.1.7 on 2021-06-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20210628_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de modificación'),
        ),
    ]
