# Generated by Django 3.2.6 on 2021-08-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20210628_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whatsapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100, unique=True, verbose_name='Numero ej: 1112341234')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de modificación')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'whatsapp',
                'verbose_name_plural': 'whatsapps',
                'ordering': ['name'],
            },
        ),
    ]
