# Generated by Django 3.2.6 on 2021-08-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=100, unique=True, verbose_name='mails ej: uno@uno.com; otro@otro.com; etc.')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de modificación')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'mail Hillel',
                'verbose_name_plural': 'mail Hillel',
                'ordering': ['mail'],
            },
        ),
        migrations.AlterModelOptions(
            name='whatsapp',
            options={'ordering': ['name'], 'verbose_name': 'whatsapp Hillel', 'verbose_name_plural': 'whatsapp Hillel'},
        ),
    ]
